receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 160
  batch: {}
exporters:
  otlphttp/phoenix:
    endpoint: http://phoenix:6006
    headers:
      x-project-name: jobsearch
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo, otlphttp/phoenix]
