'use client';
import {useEffect,useState} from 'react';
type Report={job_id:string;company:string;title:string;url:string;resume_variant:string;resume_filename:string;status:string;submitted:boolean;stale?:boolean;missing_fields:string[];next_action:string;assessment:{blocked:boolean;reason?:string;limited_source?:boolean;topics?:{topic:string;status:string;job_evidence:string;resume_evidence:string|null}[];requirements?:{text:string;status:string}[];limitations?:string[]}};
async function request(path:string,method='GET'){const r=await fetch('/api'+path,{method});const b=await r.json();if(!r.ok)throw Error(b.detail||'Unable to check application');return b}
export function ReportView({value}:{value:Report}){return <div className="intake-panel"><h3>{value.title}</h3><p>{value.company} · Resume: <strong>{value.resume_filename}</strong></p><p><strong>{value.submitted?'Submitted':value.stale?'Check out of date — run again':value.status.replaceAll('_',' ')}</strong> · {value.submitted?'Employer confirmation recorded':value.status==='submission_unknown'?'Outcome unknown — do not retry':value.status==='submitting'?'Attempt in progress':'Not submitted'}</p>{value.missing_fields.length>0&&<p>Missing profile answers: {value.missing_fields.join(', ').replaceAll('_',' ')}.</p>}
 {value.assessment.blocked?<p>{value.assessment.reason}</p>:<><p>This evidence check is not an employer ATS score. A mention does not prove experience or proficiency.</p>{value.assessment.limited_source&&<div className="message">The listing contains a summary or limited description. Compare the full employer requirements before applying.</div>}
 <h4>Topic evidence</h4>{!value.assessment.topics?.length&&<p>No recognized topics found; assess the full requirements manually.</p>}{value.assessment.topics?.map(t=><details key={t.topic}><summary>{t.topic}: {t.status==='mentioned'?'Mentioned in resume':'Not found in resume'}</summary><p><strong>Job:</strong> {t.job_evidence}</p><p><strong>Resume:</strong> {t.resume_evidence||'No evidence found. Do not add this qualification unless accurate.'}</p></details>)}
 <h4>Requirements needing verification</h4>{value.assessment.requirements?.length?<ul>{value.assessment.requirements.map((r,i)=><li key={i}>{r.text}</li>)}</ul>:<p>No explicit requirements were extracted. This does not mean the employer has no requirements.</p>}</>}
 <p>{value.next_action}</p><div className="intake-actions"><a className="primary" href={value.url} target="_blank" rel="noopener noreferrer">Open employer / source form</a><a className="secondary" href={'/api/intake/resume/'+value.resume_variant+'?download=true'}>Download selected resume</a></div></div>}
export default function ApplicationCheck({jobId}:{jobId:string}){const [value,setValue]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <section><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setValue(await request('/jobs/'+jobId+'/application-check','POST'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Checking...':'Check resume & prepare application'}</button>{error&&<p role="alert" className="message error">{error}</p>}{value&&<ReportView value={value}/>}</section>}
export function Applications({version}:{version:number}){const [rows,setRows]=useState<Report[]>([]),[error,setError]=useState('');useEffect(()=>{request('/applications').then(setRows).catch(e=>setError(e.message))},[version]);return <section>{error&&<p role="alert">{error}</p>}<div className="message">Application checks are private to your account. Opening a form does not count as submission. Agent-assisted attempts appear here with their recorded outcome. Scheduled bulk submission is not enabled.</div>{!rows.length&&<p>Open an opportunity and choose “Check resume & prepare application” to begin.</p>}{rows.map(r=><div key={r.job_id}><ReportView value={r}/><ApplicationCheck jobId={r.job_id}/></div>)}</section>}
