"use client";
import {LoaderCircle,CheckCircle2,TriangleAlert,Clock3} from 'lucide-react';
import {useEffect,useState} from 'react';
type Source={company:string;enabled:boolean;last_success_at:string|null;last_error:string|null;status:string|null;fetched:number|null;decision_counts:Record<string,number>|null;trace_id:string|null;next_scheduled_at:string|null};
type Status={sources:Source[];current_matches:number;schedule_hours:number;schedule_hour:number;schedule_timezone:string};
const names:Record<string,string>={match:'Accepted',outside_us:'Outside US',outside_role:'Outside role scope',sensitive_content:'Sensitive content rejected',unknown_location:'US location unconfirmed',title_review:'Title needs review',guardrail_review:'Content needs review',duplicate:'Duplicate source records'};
export default function CollectionStatus({version,date}:{version:number;date:string}){
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState(false);
 useEffect(()=>{let active=true;async function load(){try{const r=await fetch('/api/collection-status');if(!r.ok)throw Error();const v=await r.json();if(active){setData(v);setError(false)}}catch{if(active)setError(true)}}load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer)}},[version]);
 if(error)return <div className="message" role="status">Collection status is unavailable. Check Activity for run details.</div>;
 if(!data)return <div className="message">Checking collection status…</div>;
 const enabled=data.sources.filter(s=>s.enabled), failed=enabled.filter(s=>s.status==='failed'), pending=enabled.filter(s=>['queued','running'].includes(s.status||''));
 return <details className="collection-panel"><summary><span className="collection-indicator">{pending.length?<LoaderCircle size={16} className="spin"/>:failed.length?<TriangleAlert size={16}/>:<CheckCircle2 size={16}/>}</span>Collection status · {enabled.length} enabled boards · {data.current_matches} current matches{failed.length?` · ${failed.length} failed`:''}{pending.length?` · ${pending.length} queued/running`:''}</summary>
 <p>{!enabled.length?'No sources configured. Add an employer board in Sources.':pending.length?'Collection is in progress. Refresh opportunities when the run completes.':failed.length?'Some sources failed. Results may be incomplete; inspect Activity.':data.current_matches===0?'No current postings match the role and US-location rules.':date!=='any'?'The date filter can exclude available matches. Select Any time to include older or undated postings.':'Results reflect the most recent successful checks of the configured boards.'}</p>
 <p className="muted small">Sources are scheduled once daily at 5:00 AM Pacific time. Missed runs catch up after startup, but never before 5:00 AM. This panel updates every 30 seconds. Opportunity results update when you click Refresh. Counts below are from each board’s latest run.</p>
 {data.sources.map(s=><div className="collection-source" key={s.company}><strong>{s.company}</strong><span className="source-state" data-state={s.status||'idle'}>{s.status==='running'?<LoaderCircle size={14} className="spin"/>:s.status==='completed'?<CheckCircle2 size={14}/>:s.status==='failed'?<TriangleAlert size={14}/>:<Clock3 size={14}/>} {s.status||'Not collected'} · {s.fetched??0} fetched</span><div className="source-stages" aria-label={'Source progress: '+(s.status||'not collected')}><span data-active={['queued','running','completed','failed'].includes(s.status||'')}>Queued</span><span data-active={['running','completed','failed'].includes(s.status||'')} className={s.status==='running'?'stage-running':''}>Fetching</span><span data-active={['completed','failed'].includes(s.status||'')}>{s.status==='failed'?'Failed':s.status==='completed'?'Completed':'Result pending'}</span></div><small>Last success: {s.last_success_at?new Date(s.last_success_at).toLocaleString():'Never'} · Next scheduled: {s.next_scheduled_at?new Date(s.next_scheduled_at).toLocaleString():'Pending'}</small>{s.last_error&&<small>Failure: {s.last_error}</small>}<div className="tags">{s.decision_counts?Object.entries(s.decision_counts).map(([key,n])=><span key={key}>{names[key]||key}: {n}</span>):<span>Decision totals were not recorded for this run.</span>}</div>{s.trace_id&&<small>Trace ID: <code>{s.trace_id}</code></small>}</div>)}
 </details>
}
