export const dataGroups = [
 {name:'Data Analytics',tools:[{id:'clickhouse',name:'ClickHouse',description:'Explore the staging analytical database in the native SQL console. A separate ClickHouse account is required; no credentials are embedded here.',url:'http://localhost:3187/play',status:'Console available · ingestion pending'}]},
 {name:'Data Quality',tools:[{id:'gx',name:'Great Expectations',description:'Review validation runs, failed checks and aggregate evidence for the staging job feed.',url:'http://localhost:3185/?view=data-gx',status:'Validation results'},{id:'soda',name:'SODA',description:'Review Soda scan history and measured data-quality findings.',url:'http://localhost:3185/?view=data-soda',status:'Validation results'}]},
 {name:'Data Modelling',tools:[{id:'model',name:'PostgreSQL · SchemaSpy',description:'Inspect actual PostgreSQL tables and declared relationships in the existing model viewer.',url:'http://localhost:3185/?view=model',status:'Schema viewer'},{id:'catalog',name:'OpenMetadata · Catalog',description:'Explore the catalog of PostgreSQL tables and columns. OpenMetadata catalogs models; SchemaSpy displays the relational diagram.',url:'http://localhost:3186/',status:'Separate governance sign-in'}]},
 {name:'Data Governance',tools:[{id:'governance',name:'OpenMetadata',description:'Review glossary terms, proposed classifications and stewardship. Ownership assignments still require review.',url:'http://localhost:3186/',status:'Catalog and governance'}]},
 {name:'Data Lineage',tools:[{id:'lineage',name:'OpenMetadata · Lineage',description:'Open a catalog asset and select its Lineage tab. Pipeline lineage has not been ingested; no lineage graph is claimed yet.',url:'http://localhost:3186/',status:'Lineage ingestion pending'}]},
 {name:'Data Science',tools:[{id:'science',name:'Data Science workspace',description:'Reserved for a future notebook, experiment and model-development workspace.',url:'',status:'Not configured'}]},
 {name:'Data Engineering',tools:[{id:'ingestion',name:'Ingestion',description:'Inspect the existing staging source-discovery activity. This is not a PostgreSQL-to-ClickHouse ingestion pipeline.',url:'http://localhost:3185/?view=runs',status:'Discovery activity'},{id:'dbt',name:'dbt Core',description:'Review existing dbt validation evidence. A ClickHouse transformation project has not been configured.',url:'http://localhost:3185/?view=data-dbt',status:'Validation results'},{id:'dag',name:'DAG scheduler',description:'Reserved for scheduling and running ingestion workflows. No new DAG scheduler is installed or activated.',url:'',status:'Not configured'}]}
];
