'use client';
import {useEffect,useState} from 'react';

type Demographics={pronouns:string;gender_identity:string;sexual_orientation:string;race_ethnicity:string;gender_sex:string;veteran_status:string;disability_status:string;use_for_applications:boolean};
type Profile={demographics:Demographics;full_name:string;email:string;phone:string;location:string;linkedin_url:string;portfolio_url:string;authorized_us:string;sponsorship:string;relocate:string;workplace:string[];desired_base_usd:number|null;notice_period:string;excluded_companies:string;confirmed:boolean};
type Resume={variant:string;filename:string;characters:number};
async function call(path:string,init?:RequestInit){const r=await fetch('/api'+path,init);const b=await r.json();if(!r.ok)throw Error(b.detail||'Request failed');return b}
export default function Intake(){
 const [profile,setProfile]=useState<Profile|null>(null),[resumes,setResumes]=useState<Resume[]>([]),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(''),[deleting,setDeleting]=useState(false),[linkedinSuggested,setLinkedinSuggested]=useState(false);
 async function load(){const r=await call('/intake');const links:string[]=r.linkedin_suggestions||[];const suggest=!r.profile.linkedin_url&&links.length===1;setLinkedinSuggested(suggest);setProfile(suggest?{...r.profile,linkedin_url:links[0],confirmed:false}:r.profile);setResumes(r.resumes)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function field(key:keyof Profile,value:unknown){setProfile(p=>p?{...p,[key]:value,confirmed:key==='confirmed'?Boolean(value):false}:p)}
 if(!profile)return <div className="message">{error||'Loading your private profile...'}</div>;
 return <section className="intake"><div className="message"><strong>Your private application profile</strong><p>Resumes and answers stay in Job Search. They are encrypted in storage and are not sent to an external AI service. Complete your own answers; unknown information will not be inferred from your resume.</p></div>
 {error&&<div role="alert" className="message error">{error}</div>}{message&&<div role="status" className="message">{message}</div>}
 <h2>Resumes</h2><p>PDF, DOCX or UTF-8 TXT, up to 5 MiB. Use text-based documents. Review extracted text for missing content.</p>
 <div className="intake-grid">{[['default','Default resume','Used for other companies.'],['capital_one','Capital One resume','Used for recognized Capital One employer names.']].map(([variant,label,hint])=>{const current=resumes.find(r=>r.variant===variant);return <section className="intake-panel" key={variant}><h3>{label}</h3><p>{hint}</p><strong>{current?.filename||'No resume uploaded'}</strong>{current&&<p>{current.characters.toLocaleString()} readable characters</p>}
 <label>Upload or replace<input type="file" accept=".pdf,.docx,.txt" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;action(async()=>{if(file.size>5*1024*1024)throw Error('File exceeds 5 MiB');await call('/intake/resume/'+variant,{method:'PUT',headers:{'Content-Type':'application/octet-stream','X-Resume-Format':file.name.split('.').pop()||'','X-Resume-Name':file.name},body:file});await load();setPreview('');setMessage('Resume saved securely.')})}}/></label>
 {current&&<div className="intake-actions"><button className="secondary" disabled={busy} onClick={()=>action(async()=>{const r=await call('/intake/resume/'+variant);setPreview(r.text)})}>Review extracted text</button><a className="secondary" href={'/api/intake/resume/'+variant+'?download=true'}>Download original</a><button className="secondary" disabled={busy} onClick={()=>action(async()=>{await call('/intake/resume/'+variant,{method:'DELETE'});await load();setPreview('');setMessage('Resume and old application checks deleted.')})}>Delete resume</button></div>}</section>})}</div>
 {preview&&<details open className="intake-panel"><summary>Extracted resume text</summary><pre className="resume-preview">{preview}</pre><button className="secondary" onClick={()=>setPreview('')}>Close preview</button></details>}
 <h2>Application details</h2>{linkedinSuggested&&<p className="message">LinkedIn URL filled from your resume. Review it before saving; this suggestion has not been saved to your profile.</p>}<p>Enter contact information and work preferences. Do not enter account passwords, Social Security numbers, or date of birth. Optional demographic answers have their own section below.</p>
 <form onSubmit={e=>{e.preventDefault();action(async()=>{await call('/intake',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});setLinkedinSuggested(false);setMessage('Profile saved. Existing checks must be rerun after profile changes.')})}}>
 <fieldset disabled={busy} className="intake-grid">
 {([['full_name','Full name','text'],['email','Email','email'],['phone','Phone','tel'],['location','City, state and country','text'],['linkedin_url','LinkedIn URL (optional)','url'],['portfolio_url','Portfolio URL (optional)','url'],['notice_period','Availability / notice period (optional)','text']] as const).map(([key,label,type])=><label key={key}>{label}<input type={type} maxLength={key.includes('url')?400:key==='email'?254:key==='phone'?40:160} value={profile[key]} onChange={e=>field(key,e.target.value)}/></label>)}
 {([['authorized_us','Authorized to work in the US?'],['sponsorship','Need sponsorship now or in the future?'],['relocate','Willing to relocate?']] as const).map(([key,label])=><label key={key}>{label}<select value={profile[key]} onChange={e=>field(key,e.target.value)}><option value="unknown">Not answered</option><option value="yes">Yes</option><option value="no">No</option></select></label>)}
 <label>Desired annual base salary, USD (optional)<input type="number" min="0" max="10000000" value={profile.desired_base_usd??''} onChange={e=>field('desired_base_usd',e.target.value===''?null:Number(e.target.value))}/></label>
 <label>Exclude employers (comma-separated exact names)<input maxLength={1000} value={profile.excluded_companies} onChange={e=>field('excluded_companies',e.target.value)}/></label>
 <div><p>Workplace preferences</p>{['Remote','Hybrid','On-site'].map(v=><label className="check-label" key={v}><input type="checkbox" checked={profile.workplace.includes(v)} onChange={e=>field('workplace',e.target.checked?[...profile.workplace,v]:profile.workplace.filter(x=>x!==v))}/>{v}</label>)}</div>
 </fieldset>
 <section className="intake-panel"><h2>Optional self-identification</h2><p>These are sensitive personal details. Only enter answers you choose to disclose. They are encrypted with your profile and are not used to score jobs or included in email reports. Nothing is inferred from your resume.</p>
 <fieldset disabled={busy} className="intake-grid">
 {([['race_ethnicity','Race / ethnicity'],['gender_sex','Gender / sex']] as const).map(([key,label])=><label key={key}>{label}<input list={key+'-options'} maxLength={key==='race_ethnicity'?240:120} placeholder="Not provided" value={profile.demographics[key]} onChange={e=>field('demographics',{...profile.demographics,[key]:e.target.value,use_for_applications:false})}/><datalist id={key+'-options'}>{(key==='race_ethnicity'?['Prefer not to disclose','American Indian or Alaska Native','Asian','Black or African American','Hispanic or Latino','Native Hawaiian or Other Pacific Islander','White','Two or more races']:['Prefer not to disclose','Female','Male','Nonbinary']).map(v=><option value={v} key={v}/>)}</datalist><small>You may enter your own response. Employer categories can differ.</small></label>)}
 {([['pronouns','Pronouns',['Prefer not to disclose','He/him','She/her','They/them']],['gender_identity','Gender identity',['Prefer not to disclose','Man','Woman','Nonbinary']],['sexual_orientation','Sexual orientation',['Prefer not to disclose','Straight / heterosexual','Gay','Lesbian','Bisexual','Pansexual','Asexual']]] as const).map(([key,label,options])=><label key={key}>{label}<input aria-label={label} list={key+'-options'} maxLength={120} placeholder="Not provided" value={profile.demographics[key]||''} onChange={e=>field('demographics',{...profile.demographics,[key]:e.target.value,use_for_applications:false})}/><datalist id={key+'-options'}>{options.map(v=><option value={v} key={v}/>)}</datalist><small>Optional. Choose a suggestion or enter your own response.</small></label>)}
 <label>Protected veteran status<select value={profile.demographics.veteran_status} onChange={e=>field('demographics',{...profile.demographics,veteran_status:e.target.value,use_for_applications:false})}><option value="not_provided">Not provided</option><option value="protected_veteran">I identify as a protected veteran</option><option value="not_protected_veteran">I am not a protected veteran</option><option value="prefer_not_to_disclose">Prefer not to disclose</option></select></label>
 <label>Disability status<select value={profile.demographics.disability_status} onChange={e=>field('demographics',{...profile.demographics,disability_status:e.target.value,use_for_applications:false})}><option value="not_provided">Not provided</option><option value="yes">Yes</option><option value="no">No</option><option value="prefer_not_to_disclose">Prefer not to disclose</option></select></label>
 </fieldset><label className="check-label"><input type="checkbox" checked={profile.demographics.use_for_applications} onChange={e=>field('demographics',{...profile.demographics,use_for_applications:e.target.checked})}/>Allow the agent to use these explicit answers for matching self-identification questions on my applications.</label><p>If a question's meaning or choices differ, the agent must ask you. Not provided does not mean No or Prefer not to disclose. Submission automation is not connected yet.</p></section>
 <label className="check-label"><input type="checkbox" checked={profile.confirmed} onChange={e=>field('confirmed',e.target.checked)}/>I confirm these answers are accurate and may be used to prepare my applications.</label><button className="primary" disabled={busy}>Save profile</button></form>
 <p className="muted">Direct submission is not connected yet. Employer screening questions, declarations and consent choices must be completed using verified answers. Saving this form does not submit an application.</p>
 <div className="intake-panel"><button className="secondary" disabled={busy} onClick={()=>setDeleting(!deleting)}>Delete all my intake data</button>{deleting&&<><p>This removes your profile, both resumes and stored application checks. Existing audit events and database backups are not erased by this action.</p><button className="secondary" disabled={busy} onClick={()=>action(async()=>{await call('/intake',{method:'DELETE'});await load();setPreview('');setDeleting(false);setMessage('Your intake data has been deleted.')})}>Confirm deletion</button></>}</div>
 </section>
}
