 'use client';
import {useEffect,useState} from 'react';
import {apiFetch} from './session';
type State={model:{enabled:boolean;version:number;pinned:boolean;decisions:number;rules:{feature:string;weight:number;reason:string}[]};history:{id:number;created_at:string;decisions:number;rules:number}[]};
export default function Learning({onChange}:{onChange:()=>void}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await apiFetch('/learning',{cache:'no-store'});if(!r.ok)throw Error('Unable to load learning preferences');setState(await r.json())}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function change(action:string,version?:number){setBusy(true);setError('');try{const r=await apiFetch('/learning',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,version})});if(!r.ok)throw Error('Unable to change learning preferences');await load();onChange()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="collection-panel"><summary>Learning preferences · {state?(state.model.enabled?'Enabled':'Paused'):'Loading'}</summary><p>Uses only your job decisions. Three consistent examples are required before a bounded ranking adjustment. Eligibility, archive locks and application permissions never change.</p>{error&&<p role="alert">{error}</p>}{state&&<><p>Version {state.model.version} · {state.model.decisions} decisions · {state.model.rules.length} active rules{state.model.pinned?' · Previous version pinned':''}</p><div className="intake-actions"><button className="secondary" disabled={busy} onClick={()=>change(state.model.enabled?'pause':'resume')}>{state.model.enabled?'Pause ranking adjustments':'Resume latest learning'}</button><button className="secondary" disabled={busy} onClick={()=>change('reset')}>Start learning afresh</button>{state.model.pinned&&<button className="secondary" disabled={busy} onClick={()=>change('resume')}>Resume latest learning</button>}</div><p className="muted small">Starting afresh ignores earlier feedback for future rankings. It does not erase history or unlock jobs. You can restore a saved version below.</p>{state.model.rules.length?<ul>{state.model.rules.map((r,i)=><li key={i}>{r.weight>0?'+':''}{r.weight}: {r.reason}</li>)}</ul>:<p>No ranking changes yet: more consistent feedback is needed.</p>}<label>Restore learning version <select disabled={busy} value="" onChange={e=>e.target.value&&change('restore',Number(e.target.value))}><option value="">Choose a saved version…</option>{state.history.map(v=><option key={v.id} value={v.id}>Version {v.id} · {v.decisions} decisions · {v.rules} rules</option>)}</select></label></>}</details>
}
