'use client';
import {useEffect,useState} from 'react';
import {Activity,Flame,RefreshCw,ShieldCheck,Radio,Clock3,Database,TriangleAlert,ChevronDown} from 'lucide-react';
import './observability.css';
type Tool='prometheus'|'phoenix'|'grafana';
type Trace={trace_id:string;name:string;start_time:string|null;latency_ms:number|null;span_count:number|null;status:string};
type Result={title?:string;panels?:{id:number;title:string;available:boolean;series:{name:string;samples:{at:number|null;value:number|null}[]}[]}[];tool:Tool;available:boolean;checked_at:string;message?:string;metrics?:Record<string,number|null>;targets?:{name:string;health:string;last_scrape:string|null;duration_seconds:number|null}[];samples?:{at:number|null;value:number|null}[];traces?:Trace[]};
const fmt=(value:number|null|undefined)=>value==null?'Unavailable':value.toLocaleString(undefined,{maximumFractionDigits:1});
const when=(value:string|null)=>value?new Date(value).toLocaleString():'Not reported';
export default function Observability({version}:{version:number}){
 const [tool,setTool]=useState<Tool>('prometheus'),[data,setData]=useState<Result|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[auto,setAuto]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;let controller:AbortController|null=null;let pending=false;
 async function load(){if(pending||document.hidden)return;pending=true;controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),20000);setLoading(true);setError('');
 try{const r=await fetch('/api/observability/'+tool,{cache:'no-store',signal:controller.signal});if(!r.ok){if(r.status===401||r.status===403)setData(null);throw Error(r.status===403?'Operator access is required.':r.status===401?'Your session has expired. Sign in again.':'Monitoring request failed.')}const body:Result=await r.json();if(active)setData(body)}catch(e){if(active)setError((e as Error).name==='AbortError'?'The monitoring request timed out. Try Refresh.':(e as Error).message)}finally{clearTimeout(timeout);pending=false;if(active)setLoading(false)}}
 setData(null);load();const timer=auto?setInterval(load,30000):null;const visible=()=>{if(auto&&!document.hidden)load()};document.addEventListener('visibilitychange',visible);return()=>{active=false;controller?.abort();if(timer)clearInterval(timer);document.removeEventListener('visibilitychange',visible)};
 },[tool,auto,refresh,version]);
 const current=data?.tool===tool?data:null;
 const values=current?.samples?.filter(p=>p.at!=null&&p.value!=null)||[];
 const ymax=Math.max(1,...values.map(p=>p.value!));
 const points=values.map((p,i)=>`${20+((p.at!-values[0].at!)/Math.max(1,values[values.length-1].at!-values[0].at!))*760},${150-(p.value!/ymax)*120}`).join(' ');
 return <section className="observability-panel" aria-label="Observability tools">
 <div className="obs-intro"><div><span className="eyebrow">LIVE OPERATIONS</span><h2>Your agents, in view</h2><p>Explore service metrics and execution traces without leaving your workspace.</p></div><ShieldCheck size={40}/></div>
 <div className="obs-tabs" role="tablist" aria-label="Monitoring tool">
 <button role="tab" id="prometheus-tab" aria-selected={tool==='prometheus'} aria-controls="monitoring-content" onClick={()=>setTool('prometheus')} className={'obs-tool prometheus '+(tool==='prometheus'?'selected':'')}><Flame/><span><strong>Prometheus</strong><small>Service health & workload</small></span></button>
 <button role="tab" id="phoenix-tab" aria-selected={tool==='phoenix'} aria-controls="monitoring-content" onClick={()=>setTool('phoenix')} className={'obs-tool phoenix '+(tool==='phoenix'?'selected':'')}><Activity/><span><strong>Phoenix</strong><small>Jobsearch execution traces</small></span></button>
 <button role="tab" id="grafana-tab" aria-selected={tool==='grafana'} aria-controls="monitoring-content" onClick={()=>setTool('grafana')} className={'obs-tool grafana '+(tool==='grafana'?'selected':'')}><Radio/><span><strong>Grafana</strong><small>Operations dashboard</small></span></button>
 </div>
 <div className="obs-controls"><span role="status">{loading?<><RefreshCw size={15} className="spin"/> Fetching live data…</>:<><Clock3 size={15}/>Last updated: {current?when(current.checked_at):'Not yet'}</>}</span><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Auto-refresh every 30 seconds</label><button className="secondary" disabled={loading} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={15}/>Refresh now</button></div>
 {error&&<div role="alert" className="message error"><TriangleAlert size={18}/>{error} {current?'Previously loaded data below may be stale.':''}</div>}
 <div id="monitoring-content" role="tabpanel" aria-labelledby={tool+'-tab'} aria-busy={loading}>
 {!current? <div className="obs-empty">{loading?'Connecting to '+tool.charAt(0).toUpperCase()+tool.slice(1)+'…':'Use Refresh now to load monitoring data.'}</div>:!current.available?<div className="obs-empty"><TriangleAlert/><h3>Live data is unavailable</h3><p>{current.message}</p></div>:tool==='prometheus'?<>
 <div className="obs-stats">{[['jobsearch_queue_ready','Waiting tasks',Database],['jobsearch_queue_running','Running tasks',Activity],['jobsearch_current_matches','Current matches',Radio],['jobsearch_queue_oldest_seconds','Oldest wait · seconds',Clock3]].map(([key,title,Icon])=>{const C=Icon as typeof Activity;return <article key={key as string}><C size={20}/><strong>{fmt(current.metrics?.[key as string])}</strong><span>{title as string}</span></article>})}</div>
 <div className="obs-chart"><h3>Waiting tasks · past hour</h3><p>Actual Prometheus samples; missing samples are not treated as zero.</p>{values.length?<svg viewBox="0 0 800 190" role="img" aria-label={'Queued tasks over the past hour; maximum '+ymax}><line x1="20" y1="150" x2="780" y2="150" stroke="#cbd5e1"/><polyline fill="none" stroke="#ea580c" strokeWidth="3" points={points}/><text x="20" y="178">{new Date(values[0].at!*1000).toLocaleTimeString()}</text><text x="650" y="178">{new Date(values[values.length-1].at!*1000).toLocaleTimeString()}</text><text x="20" y="18">Peak {fmt(ymax===1&&values.every(p=>p.value===0)?0:ymax)}</text></svg>:<p className="obs-empty">No samples are available for this time window.</p>}</div>
 <h3>Monitored services</h3><div className="obs-targets">{current.targets?.map(t=><article key={t.name}><span className={'obs-health '+t.health}>{t.health}</span><strong>{t.name.replace('jobsearch-','')}</strong><small>Last scrape: {when(t.last_scrape)}</small><small>Scrape duration: {fmt(t.duration_seconds==null?null:t.duration_seconds*1000)} ms</small></article>)}</div><p className="muted small">Prometheus scrapes every 15 seconds. Current matches count all observed matches, before your personal filters and archive decisions.</p>
 </>:tool==='grafana'?<><h3>{current.title}</h3><p className="muted">{current.message}</p><div className="grafana-panels">{current.panels?.map(panel=><article className="obs-chart" key={panel.id}><h3>{panel.title}</h3>{!panel.available?<p role="status">Panel data unavailable</p>:!panel.series.length?<p>No matching series reported.</p>:panel.series.map((series,i)=>{const points=series.samples.filter(p=>p.at!=null&&p.value!=null);const max=Math.max(1,...points.map(p=>p.value!));const min=Math.min(0,...points.map(p=>p.value!));return <div key={i}><p>{series.name}: <strong>{fmt(series.samples.at(-1)?.value)}</strong>{panel.id===5||panel.id===8?' seconds':''}</p>{points.length>1&&<svg viewBox="0 0 500 100" role="img" aria-label={panel.title+' · '+series.name+' over the past hour'}><polyline fill="none" stroke="#d97706" strokeWidth="2" points={points.map(p=>`${10+(p.at!-points[0].at!)/Math.max(1,points.at(-1)!.at!-points[0].at!)*480},${85-(p.value!-min)/(max-min)*70}`).join(' ')}/><text x="10" y="98">{fmt(min)}</text><text x="10" y="12">{fmt(max)}</text></svg>}</div>})}</article>)}</div></>:<><div className="obs-trace-heading"><Activity/><div><h3>Recent Jobsearch traces</h3><p>{current.message}</p></div><span className="badge">{current.traces?.length||0} shown</span></div>{!current.traces?.length?<div className="obs-empty"><Activity size={32}/><h3>Waiting for the first trace</h3><p>New instrumented collection runs will appear here. Historical library traces are separate.</p></div>:<div className="obs-traces">{current.traces.map(t=><details key={t.trace_id}><summary><Activity size={18}/><strong>{t.name}</strong><span className={'obs-health '+(t.status==='ERROR'?'down':'unknown')}>{t.status==='UNSET'?'No outcome recorded':t.status}</span><span>{fmt(t.latency_ms)} ms</span><ChevronDown size={16}/></summary><dl><dt>Trace ID</dt><dd><code>{t.trace_id}</code></dd><dt>Started</dt><dd>{when(t.start_time)}</dd><dt>Spans</dt><dd>{fmt(t.span_count)}</dd></dl></details>)}</div>}<p className="muted small">Read-only operational metadata. Resume contents, demographic answers, prompts, and response bodies are not displayed. A trace is not proof that an application was submitted.</p></>}
 </div></section>
}
