{
  "apiVersion": "k3d.io/v1alpha5",
  "kind": "Simple",
  "metadata": {
    "name": "ai-hub-pilot"
  },
  "servers": 1,
  "agents": 0,
  "image": "rancher/k3s:v1.35.2-k3s1",
  "kubeAPI": {
    "host": "127.0.0.1",
    "hostIP": "127.0.0.1",
    "hostPort": "6447"
  },
  "options": {
    "runtime": {
      "serversMemory": "4g",
      "hostPidMode": false
    },
    "k3d": {
      "wait": true,
      "timeout": "180s",
      "disableLoadbalancer": true
    },
    "kubeconfig": {
      "updateDefaultKubeconfig": false,
      "switchCurrentContext": false
    },
    "k3s": {
      "extraArgs": [
        {
          "arg": "--disable=traefik,servicelb",
          "nodeFilters": [
            "server:*"
          ]
        }
      ]
    }
  }
}
